/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
package org.opensearch.neuralsearch.rest;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

import lombok.SneakyThrows;
import org.apache.hc.core5.http.HttpHeaders;
import org.apache.hc.core5.http.io.entity.EntityUtils;
import org.apache.hc.core5.http.message.BasicHeader;
import org.opensearch.client.Response;
import org.opensearch.common.xcontent.XContentHelper;
import org.opensearch.common.xcontent.XContentType;
import org.opensearch.neuralsearch.BaseNeuralSearchIT;

import com.google.common.collect.ImmutableList;

import static org.opensearch.neuralsearch.util.TestUtils.DEFAULT_USER_AGENT;

/**
 * Characterizes whether ingest pipelines run for different write operations.
 *
 * WHY THIS EXISTS
 * ---------------
 * ASE routes data from original_field -> semantic_field using a standard `set` (copy) or
 * `rename` ingest processor. Embeddings are then generated by SemanticFieldProcessor, which is
 * a SYSTEM ingest processor.
 *
 * Per the OpenSearch docs, these two have different triggering rules:
 *   - default_pipeline / final_pipeline: NOT triggered by bulk partial updates
 *   - system ingest pipeline: ALWAYS triggered, including bulk partial updates
 *
 * If that is true, a bulk partial update to the original field would leave the semantic field
 * stale while still regenerating the embedding -> silently stale embeddings.
 *
 * These tests use a plain `set` processor as a stand-in for ASE's routing step, so they need no
 * deployed model and run fast. They deliberately assert the PREDICTED behavior; a failure here
 * is itself the finding, so assertion messages report the observed value.
 */
public class IngestPipelineUpdateSemanticsIT extends BaseNeuralSearchIT {

    private static final String INDEX_NAME = "pipeline-update-semantics-it";
    private static final String PIPELINE_NAME = "routing-pipeline-it";

    private static final String SOURCE_FIELD = "title";
    private static final String COPY_FIELD = "title_copy";

    @Override
    public void tearDown() throws Exception {
        super.tearDown();
        try {
            deleteIndex(INDEX_NAME);
        } catch (Exception ignored) {}
        try {
            deleteIngestPipeline(PIPELINE_NAME);
        } catch (Exception ignored) {}
    }

    // ==========================================================================
    // default_pipeline
    // ==========================================================================

    /** Baseline: a normal index request runs the default pipeline. */
    @SneakyThrows
    public void testDefaultPipeline_indexDocument_routingRuns() {
        setupPipelineAndIndex("index.default_pipeline");

        indexDocument("1", "original");

        assertEquals("Normal index should populate the copy field", "original", getField("1", COPY_FIELD));
    }

    /**
     * THE KEY TEST. If the copy field does not update, ASE's routing silently misses bulk
     * partial updates while the system processor still re-embeds -> stale embeddings.
     */
    @SneakyThrows
    public void testDefaultPipeline_bulkPartialUpdate_routingDoesNotRun() {
        setupPipelineAndIndex("index.default_pipeline");

        indexDocument("1", "original");
        assertEquals("precondition", "original", getField("1", COPY_FIELD));

        bulkPartialUpdate("1", "updated", false);

        String source = getField("1", SOURCE_FIELD);
        String copy = getField("1", COPY_FIELD);

        assertEquals("Source field should reflect the update", "updated", source);
        assertEquals(
            String.format(
                Locale.ROOT,
                "Bulk partial update should NOT run default_pipeline, so the copy field should be "
                    + "STALE. Observed source=[%s] copy=[%s]",
                source,
                copy
            ),
            "original",
            copy
        );
    }

    /** Contrast: single updates DO trigger the default pipeline. */
    @SneakyThrows
    public void testDefaultPipeline_singleUpdate_routingRuns() {
        setupPipelineAndIndex("index.default_pipeline");

        indexDocument("1", "original");
        singleUpdate("1", "updated");

        String copy = getField("1", COPY_FIELD);
        assertEquals(String.format(Locale.ROOT, "Single update SHOULD run default_pipeline. Observed copy=[%s]", copy), "updated", copy);
    }

    /** Candidate workaround: doc_as_upsert should re-trigger the pipeline. */
    @SneakyThrows
    public void testDefaultPipeline_bulkPartialUpdateDocAsUpsert_routingRuns() {
        setupPipelineAndIndex("index.default_pipeline");

        indexDocument("1", "original");
        bulkPartialUpdate("1", "updated", true);

        String copy = getField("1", COPY_FIELD);
        assertEquals(String.format(Locale.ROOT, "doc_as_upsert SHOULD run default_pipeline. Observed copy=[%s]", copy), "updated", copy);
    }

    // ==========================================================================
    // final_pipeline — confirms switching to final_pipeline does NOT fix the gap
    // ==========================================================================

    @SneakyThrows
    public void testFinalPipeline_indexDocument_routingRuns() {
        setupPipelineAndIndex("index.final_pipeline");

        indexDocument("1", "original");

        assertEquals("Normal index should populate the copy field via final_pipeline", "original", getField("1", COPY_FIELD));
    }

    @SneakyThrows
    public void testFinalPipeline_bulkPartialUpdate_routingDoesNotRun() {
        setupPipelineAndIndex("index.final_pipeline");

        indexDocument("1", "original");
        assertEquals("precondition", "original", getField("1", COPY_FIELD));

        bulkPartialUpdate("1", "updated", false);

        String source = getField("1", SOURCE_FIELD);
        String copy = getField("1", COPY_FIELD);

        assertEquals("Source field should reflect the update", "updated", source);
        assertEquals(
            String.format(
                Locale.ROOT,
                "Bulk partial update should NOT run final_pipeline either, so final_pipeline does not "
                    + "close the staleness gap. Observed source=[%s] copy=[%s]",
                source,
                copy
            ),
            "original",
            copy
        );
    }

    /** Confirms the doc_as_upsert workaround also applies to final_pipeline, not just default_pipeline. */
    @SneakyThrows
    public void testFinalPipeline_bulkPartialUpdateDocAsUpsert_routingRuns() {
        setupPipelineAndIndex("index.final_pipeline");

        indexDocument("1", "original");
        bulkPartialUpdate("1", "updated", true);

        String copy = getField("1", COPY_FIELD);
        assertEquals(String.format(Locale.ROOT, "doc_as_upsert SHOULD run final_pipeline. Observed copy=[%s]", copy), "updated", copy);
    }

    /**
     * A request-level ?pipeline= overrides default_pipeline but must NOT override final_pipeline.
     * Confirms the one advantage final_pipeline genuinely has.
     */
    @SneakyThrows
    public void testFinalPipeline_requestLevelPipelineOverride_routingStillRuns() {
        // An unrelated pipeline the caller passes explicitly
        putIngestPipeline("unrelated-pipeline-it", "{\"processors\":[{\"set\":{\"field\":\"marker\",\"value\":\"x\"}}]}");
        try {
            setupPipelineAndIndex("index.final_pipeline");

            Map<String, String> params = new HashMap<>();
            params.put("refresh", "true");
            params.put("pipeline", "unrelated-pipeline-it");
            makeRequest(
                client(),
                "PUT",
                "/" + INDEX_NAME + "/_doc/1",
                params,
                toHttpEntity("{\"" + SOURCE_FIELD + "\":\"original\"}"),
                ImmutableList.of(new BasicHeader(HttpHeaders.USER_AGENT, DEFAULT_USER_AGENT))
            );

            String copy = getField("1", COPY_FIELD);
            assertEquals("marker from the request-level pipeline should be present", "x", getField("1", "marker"));
            assertEquals(
                String.format(Locale.ROOT, "final_pipeline should still run despite ?pipeline=. Observed copy=[%s]", copy),
                "original",
                copy
            );
        } finally {
            try {
                deleteIngestPipeline("unrelated-pipeline-it");
            } catch (Exception ignored) {}
        }
    }

    // ==========================================================================
    // Helpers
    // ==========================================================================

    /** Create a `set` processor pipeline (stand-in for ASE copy mode) and attach via the given setting. */
    private void setupPipelineAndIndex(String pipelineSetting) throws Exception {
        putIngestPipeline(
            PIPELINE_NAME,
            "{\"description\":\"stand-in for ASE copy mode\",\"processors\":[{\"set\":{\"field\":\""
                + COPY_FIELD
                + "\",\"value\":\"{{"
                + SOURCE_FIELD
                + "}}\"}}]}"
        );
        createIndex(
            INDEX_NAME,
            "{\"settings\":{\""
                + pipelineSetting
                + "\":\""
                + PIPELINE_NAME
                + "\"},"
                + "\"mappings\":{\"properties\":{\""
                + SOURCE_FIELD
                + "\":{\"type\":\"text\"},\""
                + COPY_FIELD
                + "\":{\"type\":\"text\"}}}}"
        );
    }

    private void putIngestPipeline(String name, String body) throws Exception {
        makeRequest(
            client(),
            "PUT",
            "/_ingest/pipeline/" + name,
            null,
            toHttpEntity(body),
            ImmutableList.of(new BasicHeader(HttpHeaders.USER_AGENT, DEFAULT_USER_AGENT))
        );
    }

    private void indexDocument(String id, String titleValue) throws Exception {
        Map<String, String> params = new HashMap<>();
        params.put("refresh", "true");
        makeRequest(
            client(),
            "PUT",
            "/" + INDEX_NAME + "/_doc/" + id,
            params,
            toHttpEntity("{\"" + SOURCE_FIELD + "\":\"" + titleValue + "\"}"),
            ImmutableList.of(new BasicHeader(HttpHeaders.USER_AGENT, DEFAULT_USER_AGENT))
        );
    }

    /** Bulk partial update. Newline-delimited with a trailing newline, as _bulk requires. */
    private void bulkPartialUpdate(String id, String newTitle, boolean docAsUpsert) throws Exception {
        String action = "{\"update\":{\"_index\":\"" + INDEX_NAME + "\",\"_id\":\"" + id + "\"}}\n";
        String doc = docAsUpsert
            ? "{\"doc\":{\"" + SOURCE_FIELD + "\":\"" + newTitle + "\"},\"doc_as_upsert\":true}\n"
            : "{\"doc\":{\"" + SOURCE_FIELD + "\":\"" + newTitle + "\"}}\n";

        Map<String, String> params = new HashMap<>();
        params.put("refresh", "true");
        Response response = makeRequest(
            client(),
            "POST",
            "/_bulk",
            params,
            toHttpEntity(action + doc),
            ImmutableList.of(new BasicHeader(HttpHeaders.USER_AGENT, DEFAULT_USER_AGENT))
        );
        String body = EntityUtils.toString(response.getEntity());
        assertFalse("bulk update reported an error: " + body, body.contains("\"error\""));
    }

    private void singleUpdate(String id, String newTitle) throws Exception {
        Map<String, String> params = new HashMap<>();
        params.put("refresh", "true");
        makeRequest(
            client(),
            "POST",
            "/" + INDEX_NAME + "/_update/" + id,
            params,
            toHttpEntity("{\"doc\":{\"" + SOURCE_FIELD + "\":\"" + newTitle + "\"}}"),
            ImmutableList.of(new BasicHeader(HttpHeaders.USER_AGENT, DEFAULT_USER_AGENT))
        );
    }

    /** Fetch a single field from _source, or null if absent. */
    @SuppressWarnings("unchecked")
    private String getField(String id, String field) throws Exception {
        Response response = makeRequest(
            client(),
            "GET",
            "/" + INDEX_NAME + "/_doc/" + id,
            null,
            null,
            ImmutableList.of(new BasicHeader(HttpHeaders.USER_AGENT, DEFAULT_USER_AGENT))
        );
        Map<String, Object> map = XContentHelper.convertToMap(
            XContentType.JSON.xContent(),
            EntityUtils.toString(response.getEntity()),
            false
        );
        Map<String, Object> source = (Map<String, Object>) map.get("_source");
        Object value = source == null ? null : source.get(field);
        return value == null ? null : value.toString();
    }
}
